### ISSUE TITLE
GitHub action for building wheels upon publication of v3.4.0.0rc1 was not triggered

### ISSUE THREAD

**Issue by chrispap95** [scikit-hep/fastjet#123]
The title says it all... 
I might try deleting the published release and re-publishing later. Any other suggestions are welcome.

**Comment by henryiii** [comment]
We can download the wheels from a manual run and publish them manually.

**Comment by jpivarski** [comment]
I confirm that creating a release used to trigger the deployment action.

_Sometimes_ they fail to trigger for intermittent reasons and you can get it to work just by creating a v3.4.0.0rc2 release. Naturally, that wouldn't work if it's a configuration file problem.

Another issue I've had in the past is formatting the "`vX.Y.Z`" tag and "`Version X.Y.Z`" release name—I've misspelled the word "version." That's not what happened here, though. (Just checked.)

**Comment by henryiii** [comment]
You can also unrelease and rerelease.

**Comment by henryiii** [comment]
I deleted the release then rereleased on the old tag. It triggered the workflow.
