### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by chrispap95** [scikit-hep/fastjet#136]
While troubleshooting configuring and building on MacOS, I realized that we haven't enabled the thread safety option that exists since 3.4.0. Do we want to recompile with that on? I am wondering whether this would solve the issue in #131 without that ugly patch.

**Comment by lgray** [comment]
That we should give a try - given the annoyingness of getting macos to go and that it should not stop us from releasing `3.4.0.0`. I'd check quick and if it simplifies the build in linux good.

**Comment by chrispap95** [comment]
After testing this on my fork, unfortunately, the seg fault is resolved by neither `--enable-limited-thread-safety` nor `--enable-thread-safety`.  Nevertheless, both options seem to pass the tests as expected when the patch is applied. However, I am not sure how useful they are in our use case. (I have a feeling they are not)

**Comment by chrispap95** [comment]
I don't think this is important for now so closing. Feel free to reopen if necessary.
