### ISSUE TITLE
Upgrade to `awkward` 2.0.0

### ISSUE THREAD

**Issue by jmduarte** [scikit-hep/fastjet#155]
After `awkward` updated to 2.0.0, CI broke: See https://github.com/scikit-hep/fastjet/actions/runs/3678235330/jobs/6221244725 on the current `main` branch.

We should update to fix this. I'm guessing `ak.layout` moved to somewhere else @jpivarski ?
```python
    def _check_general_jaggedness(self, data):
        out = isinstance(
            data.layout,
            (
>               ak.layout.IndexedArray64,
                ak.layout.IndexedArray32,
                ak.layout.IndexedArrayU32,
                ak.layout.ByteMaskedArray,
                ak.layout.BitMaskedArray,
                ak.layout.UnmaskedArray,
                ak.layout.IndexedOptionArray64,
                ak.layout.IndexedOptionArray32,
                ak.layout.Record,
            ),
        )
E       AttributeError: module 'awkward' has no attribute 'layout'
```

**Comment by jpivarski** [comment]
For this one,

```
ak.layout.IndexedArray64           →   ak.contents.IndexedArray
ak.layout.IndexedArray32           →
ak.layout.IndexedArrayU32          →
ak.layout.ByteMaskedArray          →   ak.contents.ByteMaskedArray
ak.layout.BitMaskedArray           →   ak.contents.BitMaskedArray       
ak.layout.UnmaskedArray            →   ak.contents.UnmaskedArray
ak.layout.IndexedOptionArray64     →   ak.contents.IndexedOptionArray
ak.layout.IndexedOptionArray32     →
ak.layout.Record                   →   ak.record.Record
```

But I could probably switch everything in one quick swoop. What's the procedure for checking out the latest working branch (`main`?), building, and running tests?

I'll do it in an environment with old Awkward to verify that the tests run, then do it again with new Awkward, quickly fix up all of the name changes (and anything that might be more subtle than that, though I don't expect it), and then submit a PR with the fixes.

**Comment by jpivarski** [comment]
(It has been a while since I tried to build this. I noticed that it needs `git clone --recursive`, and now I need to install `autoconf`.)

If you have a known short list of instructions, it could be good to put them in a CONTRIBUTING.md. (Apologies that we didn't do that when we first set up this repo!)

**Comment by jmduarte** [comment]
I usually do my work in a docker container with this `Dockerfile`:

```Dockerfile
from quay.io/pypa/manylinux2014_x86_64:2022-10-25-fbea779

RUN yum update -y && \
    yum install -y mpfr-devel && \
    curl -L https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.bz2 -o boost_1_80_0.tar.bz2 && \
    tar --bzip2 -xf boost_1_80_0.tar.bz2 && \
    mv boost_1_80_0/boost /usr/include/boost
ENV PATH=/opt/python/cp39-cp39/bin:$PATH
RUN git clone --recurse-submodules https://github.com/scikit-hep/fastjet --single-branch -b main
COPY src/_ext.cpp fastjet/src/_ext.cpp
COPY setup.py fastjet/setup.py
RUN cd fastjet && pip install -v '.[test]'
```

**Comment by jpivarski** [comment]
I don't remember how to use docker. It apparently hasn't been installed on this machine, so I'll have to go into another sub-task to do that.

(I've been using conda for encapsulation.)

Also, with `autoconf` and `libtool-bin`, I have all of the compilation tools that I need. There's a compilation error and _I just can't find the error message!_ I'll keep looking/trying to figure out _some_ way to proceed.

**Comment by jpivarski** [comment]
Okay, it compiled in my conda environment with the old Awkward (I needed to `conda install swig`). The error message was hard to find because whole configure scripts get printed out—I assume that you needed that for debugging at some point.

Now that `pip install .[test]` has been successful, it can't `import fastjet` because

```
>>> import fastjet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/mambaforge/envs/old-awkward/lib/python3.11/site-packages/fastjet/__init__.py", line 8, in <module>
    import fastjet._pyjet  # noqa: F401, E402
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jpivarski/mambaforge/envs/old-awkward/lib/python3.11/site-packages/fastjet/_pyjet.py", line 7, in <module>
    from fastjet.__init__ import ClusterSequence
  File "/home/jpivarski/mambaforge/envs/old-awkward/lib/python3.11/site-packages/fastjet/__init__.py", line 24, in <module>
    from fastjet._swig import ClusterSequence_fastjet_banner_stream  # noqa: F401, E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'ClusterSequence_fastjet_banner_stream' from 'fastjet._swig' (/home/jpivarski/mambaforge/envs/old-awkward/lib/python3.11/site-packages/fastjet/_swig.py)
```

I checked, and there isn't any object named `ClusterSequence_fastjet_banner_stream` in any Python file. Oh! It's supposed to be in the extension library,

```
% fgrep -r ClusterSequence_fastjet_banner_stream .
...
grep: ./build/lib.linux-x86_64-cpython-311/fastjet/_fastjet_core/lib/python3.11/site-packages/_fastjet.so.0.0.0: binary file matches
grep: ./build/lib.linux-x86_64-cpython-311/fastjet/_fastjet_core/lib/python3.11/site-packages/_fastjet.a: binary file matches
...
```

Both of these binaries have a name like that, but it starts with `_wrap_`:

```
% nm ./build/lib.linux-x86_64-cpython-311/fastjet/_fastjet_core/lib/python3.11/site-packages/_fastjet.so.0.0.0 | fgrep ClusterSequence_fastjet_banner_stream
000000000006b290 t _wrap_ClusterSequence_fastjet_banner_stream

% nm ./build/lib.linux-x86_64-cpython-311/fastjet/_fastjet_core/lib/python3.11/site-packages/_fastjet.a | fgrep ClusterSequence_fastjet_banner_stream
00000000000196e0 t _wrap_ClusterSequence_fastjet_banner_stream
```

Maybe I'll just go through the codebase, rename everything that I know to rename, and _not_ try to compile it. I'll have to debug it through CI.

**Comment by jmduarte** [comment]
Ah yes, this is related to #140

**Comment by jpivarski** [comment]
I was doing a fresh compilation each time, not building incrementally. (I even threw out the git repo and re-cloned on each attempt.)

At the moment, though, I'm deep into replacing names. I might get it in one or two times with the CI.
