### ISSUE TITLE
Possible to support aarch64 wheels?

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/fastjet#165]
:wave: Hi. Would it be possible to support `manylinux2014_aarch64` wheels on PyPI, like [`awkward-cpp` does](https://pypi.org/project/awkward-cpp/5/#files)? As there aren't any available at the moment this means that you need to install from sdist when doing a multi-platform `docker buildx` build (`--platform linux/amd64,linux/arm64`) to provide Docker images that can run without heavy emulation on M1/M2 Macs. I'm currently in the process of trying to do this, and it is a bit trickier than just building for Ubuntu.

**Comment by lgray** [comment]
We'd need a hosted aarch64 runner for that, qemu would take *forever* (x86 builds are 34 minutes!). I am happy to setup a self-hosted aarch64 build machine, I've got some spare cores.

Just to stick a pin in it we should also think about dask_awkward integration.

**Comment by lgray** [comment]
Or we could only spin out wheels for x86/arm64, testing just on arm64 and assume some risk.

**Comment by lgray** [comment]
At the very least I'll give a go to building it on the arm64 machine(s) I've got to see if it completes.

**Comment by chrispap95** [comment]
> Just to stick a pin in it we should also think about dask_awkward integration.

Hi @lgray, how do you imagine dask_awkward integration happening? Do you have any examples from other projects that have already done it?

**Comment by henryiii** [comment]
I believe Cirrus CI has aarch machines.

**Comment by lgray** [comment]
@chrispap95 I think it's not too bad in this case, we could probably even make a decorator to behave differently between `ak` and `dak`. Mostly we need to wrap the various fastjet calls in `dask_awkward.map_partitions` and make sure the predictions of the output (awkward forms) are accurate. 

See examples for regular awkward functionality:
https://github.com/dask-contrib/dask-awkward/pull/133

**Comment by jmduarte** [comment]
Who should we ask about adding Cirrus CI to scikit-hep? 

https://github.com/marketplace/cirrus-ci/order/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW45OTA=?account=scikit-hep

It's free for public repos. So this would be a good way to speed things up for `aarch64` tests/builds.

**Comment by matthewfeickert** [comment]
> Who should we ask about adding Cirrus CI to scikit-hep?


@jmduarte I enabled it for scikit-hep/fastjet (only) for the time being. After I turned it on I was directed to https://cirrus-ci.org/guide/quick-start/?installation_id=32808992&setup_action=install
