### ISSUE TITLE
dask_awkward support in fastjet

### ISSUE THREAD

**Issue by lgray** [scikit-hep/fastjet#188]
So coffea is getting very close to complete with the awkward2 + dask_awkward upgrade.

It would be great if fastjet would interoperate with dask_awkward easily, so that users don't have to define their own map_partitions calls to access all the functionality of fastjet properly through dask.

I can start a PR with a few examples but I would appreciate some help to make sure we get complete coverage! It shouldn't be that difficult to do.

**Comment by chrispap95** [comment]
I have wanted for some time to work on this but I wasn't sure how to begin. You can count me in.

**Comment by lgray** [comment]
@andrzejnovak for haCATthon?
