### ISSUE TITLE
exclusive_jets_up_to()

### ISSUE THREAD

**Issue by cshimmin** [scikit-hep/fastjet#219]
It would be very useful to expose the functionality of ClusterSequence::exclusive_jets_up_to() in the awkward/multievent interface. I see that exclusive_subjets_up_to is implemented, so I assume it is possible and maybe even easy if that function can be partly copied.

I was prepared to try and implement it myself, but unfortunately I burned all the time I had budgeted for this fighting with the build system. Currently setup.py overwrites CXXFLAGS and LDFLAGS so there is no easy way to pass nonstandard include/lib dirs. That's a pretty easy fix, but the real limitation is fj-contrib's very poor build system, which hardcodes g++ instead of using $(CXX) and doesn't use LDFLAGS at all. At that point I gave up :/

**Comment by lgray** [comment]
Yeah making the build system cmake instead of the current system is something we'd like, but we're not the code owners so that may take some time.

**Comment by cshimmin** [comment]
Yeah totally understandable, not meant to be an indictment of the skhep/fastjet project at all. Just wish I could have contributed a working feature :) For now with work constraints I will have to stick with the object interface to use this feature. But if someone with the know-how could make this happen, there are definitely real-world uses for it!
