### ISSUE TITLE
problem in installation fastjet inside ma5-2.0.4_beta

### ISSUE THREAD

**Issue by mehep** [scikit-hep/fastjet#266]
Hi. ma5 team, thanks a lot for your developing this tool

When trying to install Fastjet within ma5 , it fails
This is the msg I get: 
------------------------
MA5-ERROR: impossible to configure the project. For more details, see the log file:
MA5-ERROR: /home/aitelkadi/Desktop/madanalysis5-2.0.4_beta/tools/fastjet/configuration_contrib.log
MA5:    Installation NOT complete.
MA5:    Elapsed time = 3.32 seconds
MA5:    => Status: [FAILURE]
------------------------

how can i solve this issue ?
best regards

**Comment by lgray** [comment]
Can you not use `pip` within madanalysis? If not you may want to consider that, it would significantly simplify your life and project scope.

**Comment by lgray** [comment]
That is not the correct course of action. 

You should not need to use mad analysis's installation feature to get these python fastjet bindings into your environment.
You *only* need to `pip install fastjet` into your local python environment to use this package. 
There is no need to install this package using madanalysis's installation tools.

**Comment by jpivarski** [comment]
madanalysis5 has [its own installation mechanism](https://github.com/MadAnalysis/madanalysis5/blob/main/madanalysis/install/install_manager.py) and [installs C++ FastJet](https://github.com/MadAnalysis/madanalysis5/blob/main/madanalysis/install/install_fastjet.py) (not this package) as part of its canned [set of 12 packages](https://github.com/MadAnalysis/madanalysis5/blob/e0683e829ef6a0a7e3870c85b1a7723d58c7ce2c/madanalysis/install/install_manager.py#L41-L90) that it knows how to work with.

In that kind of closed environment, I doubt there would be any way to _integrate_ Python fastjet (this package) with madanalysis5. At best, they could be used side-by-side in the same Python environment (just to set expectations). I think madanalysis5 would need explicit code to recognize Python fastjet (this package) to have them both operate on the same data.

If madanalysis5 presents arrays of pseudojets as NumPy arrays, it may be possible to hand off data between them in a streamlined way.

**Comment by chrispap95** [comment]
This is clearly related to madanalysis5 and how it handles the C++ fastjet compilation. Not related to the fastjet python bindings. Closing for now. Reopen if needed.
