### ISSUE TITLE
Having trouble doing pip install fastjet - failed building wheel

### ISSUE THREAD

**Issue by rmsnyder8421** [scikit-hep/fastjet#293]
Hi,

I'm sorry if I'm missing something on my end, but for some reason the wheel can't build in fastjet. Here is the error output I get:

$ pip install fastjet
Defaulting to user installation because normal site-packages is not writeable
Collecting fastjet
  Using cached fastjet-3.4.1.3.tar.gz (4.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-312
      creating build/lib.linux-x86_64-cpython-312/fastjet
      copying src/fastjet/__init__.py -> build/lib.linux-x86_64-cpython-312/fastjet
      copying src/fastjet/_generalevent.py -> build/lib.linux-x86_64-cpython-312/fastjet
      copying src/fastjet/_multievent.py -> build/lib.linux-x86_64-cpython-312/fastjet
      copying src/fastjet/_pyjet.py -> build/lib.linux-x86_64-cpython-312/fastjet
      copying src/fastjet/_singleevent.py -> build/lib.linux-x86_64-cpython-312/fastjet
      copying src/fastjet/_utils.py -> build/lib.linux-x86_64-cpython-312/fastjet
      copying src/fastjet/version.py -> build/lib.linux-x86_64-cpython-312/fastjet
      running egg_info
      writing src/fastjet.egg-info/PKG-INFO
      writing dependency_links to src/fastjet.egg-info/dependency_links.txt
      writing requirements to src/fastjet.egg-info/requires.txt
      writing top-level names to src/fastjet.egg-info/top_level.txt
      ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any
      reading manifest file 'src/fastjet.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '.git' found anywhere in distribution
      warning: no previously-included files matching '.gitmodules' found anywhere in distribution
      warning: no files found matching 'patch_fastjet_i.txt'
      warning: no previously-included files found matching '.cirrus.yml'
      adding license file 'LICENSE'
      writing manifest file 'src/fastjet.egg-info/SOURCES.txt'
      running build_ext
      error: [Errno 2] No such file or directory: 'patch'
pyproject.toml) ... done
Collecting awkward>=2 (from fastjet)
  Using cached awkward-2.6.4-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: numpy>=1.13.3 in /usr/lib64/python3.12/site-packages (from fastjet) (1.26.4)
Requirement already satisfied: vector in ./.local/lib/python3.12/site-packages (from fastjet) (1.4.0)
Collecting awkward-cpp==33 (from awkward>=2->fastjet)
  Using cached awkward_cpp-33-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.2 kB)
Collecting fsspec>=2022.11.0 (from awkward>=2->fastjet)
  Using cached fsspec-2024.3.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: packaging in ./.local/lib/python3.12/site-packages (from awkward>=2->fastjet) (20.9)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/lib/python3.12/site-packages (from packaging->awkward>=2->fastjet) (3.1.2)
Using cached awkward-2.6.4-py3-none-any.whl (791 kB)
Using cached awkward_cpp-33-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (692 kB)
Using cached fsspec-2024.3.1-py3-none-any.whl (171 kB)
Building wheels for collected packages: fastjet
  Building wheel for fastjet (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for fastjet (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-312
      creating build/lib.linux-x86_64-cpython-312/fastjet
      copying src/fastjet/__init__.py -> build/lib.linux-x86_64-cpython-312/fastjet
      copying src/fastjet/_generalevent.py -> build/lib.linux-x86_64-cpython-312/fastjet
      copying src/fastjet/_multievent.py -> build/lib.linux-x86_64-cpython-312/fastjet
      copying src/fastjet/_pyjet.py -> build/lib.linux-x86_64-cpython-312/fastjet
      copying src/fastjet/_singleevent.py -> build/lib.linux-x86_64-cpython-312/fastjet
      copying src/fastjet/_utils.py -> build/lib.linux-x86_64-cpython-312/fastjet
      copying src/fastjet/version.py -> build/lib.linux-x86_64-cpython-312/fastjet
      running egg_info
      writing src/fastjet.egg-info/PKG-INFO
      writing dependency_links to src/fastjet.egg-info/dependency_links.txt
      writing requirements to src/fastjet.egg-info/requires.txt
      writing top-level names to src/fastjet.egg-info/top_level.txt
      ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any
      reading manifest file 'src/fastjet.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '.git' found anywhere in distribution
      warning: no previously-included files matching '.gitmodules' found anywhere in distribution
      warning: no files found matching 'patch_fastjet_i.txt'
      warning: no previously-included files found matching '.cirrus.yml'
      adding license file 'LICENSE'
      writing manifest file 'src/fastjet.egg-info/SOURCES.txt'
      running build_ext
      error: [Errno 2] No such file or directory: 'patch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fastjet
Failed to build fastjet
ERROR: Could not build wheels for fastjet, which is required to install pyproject.toml-based projects

Thanks,

**Comment by lgray** [comment]
We hadn't made a release yet with python 3.12, which was added quite some time ago.

A new release is being built now. https://github.com/scikit-hep/fastjet/releases/tag/v3.4.2.0

That will produce python 3.12 wheels and you shouldn't need to compile it yourself.

All you have to do to fix your problem is wait a bit!

**Comment by rmsnyder8421** [comment]
Thanks so much! I'll try using virtual environments.

**Comment by lgray** [comment]
Sure - if you're not tied to python 3.12 and can use 3.11, you should just be able to install fastjet with no compilation needed. :-)
