### ISSUE TITLE
fastjet is not numpy 2 compatible

### ISSUE THREAD

**Issue by lgray** [scikit-hep/fastjet#309]
All that needs to be done is to move to pybind11 >= 2.12 and to also compile against numpy 2 when building.

**Comment by matthewfeickert** [comment]
Related question: As the `pybind11` docs don't specifically mention a Git submodule as being the preferred method (https://pybind11.readthedocs.io/en/stable/installing.html) is there any reason we need to have it and don't just have it as a `pip` installable build requirement?

**Comment by matthewfeickert** [comment]
@Kwaizer can you take a look at trying to make a PR to address this? Maybe just focus on @lgray's suggestions and then we can follow up on mine later.
