### ISSUE TITLE
Tag 3.4.3 is missing

### ISSUE THREAD

**Issue by yurivict** [scikit-hep/fastjet#323]
The website has [3.4.3](https://fastjet.fr/repo/fastjet-3.4.3.tar.gz) but the last tag here is [v3.4.2.1](https://github.com/scikit-hep/fastjet/releases/tag/v3.4.2.1).

**Comment by matthewfeickert** [comment]
@yurivict Closing as this is a known issue and a decision to not publish additional releases until issues with the wheel size that are causing problems with publishing all releases to PyPI and Issues like https://github.com/scikit-hep/fastjet/issues/310 are resolved.
