### ISSUE TITLE
No module named fastjet._swig 

### ISSUE THREAD

**Issue by ssrothman** [scikit-hep/fastjet#88]
When I compile fastjet from source (ie with pip install -e .), the installation completes successfully. However, on import, I get an error: `ModuleNotFoundError: No module named 'fastjet._swig'`. What could be causing this?

**Comment by aryan26roy** [comment]
Hi @ssrothman, are you using Python3.9? It seems that the CI is encountering the same problem with Python 3.9.

**Comment by ssrothman** [comment]
Indeed I am using Python3.9. Should I just switch to 3.8?
