### ISSUE TITLE
Checklist of needs for release `v3.3.4.0`

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/fastjet#95]
At SciPy 2022 @aryan26roy (also @jpivarski too briefly) and I talked a bit about what is blocking release `v3.3.4.0` of `fasjet` so that there could be a stable release on PyPI. @aryan26roy had mentioned there was some CI build issue and I don't remember what else.

@aryan26roy if you and @jpivarski could summarize what needs to get done for a release that would be quite useful in general so that people can stop using `python -m pip install --pre` to get the release candidates (and get a release instead).

**Comment by jpivarski** [comment]
It has been long enough since I've looked at this that I'd have to just try it to get reminded what goes wrong. Something couldn't compile. Do you want access to try it?

**Comment by matthewfeickert** [comment]
> It has been long enough since I've looked at this that I'd have to just try it to get reminded what goes wrong. Something couldn't compile.

Yeah that's what I remember @aryan26roy mentioning but I don't remember _what_ in particular. Hopefully he does.

> Do you want access to try it?

Sure, if I need access. I'm also happy to try to reproduce on my fork to keep build noise down here. I won't have much time to actually look at this in the near future, but I would like to do what I can to help get `fastjet` a stable release on PyPI.

**Comment by aryan26roy** [comment]
The reason why we didn't go through with making a full release was CGAL. The wheel building breaks down when CGAL is enabled for some reason. To make a pre-release, we disabled it and I made this PR (#70 ) as a reminder that we need to switch CGAL enabled building back on. While this is not essential to a release, we did promise a fully decked out version of fastjet on Python, hence the lack of full release.
This was back in 2021, everything was fine with CGAL disabled until one of the bot PRs broke the CI recently. I remember me and @jpivarski narrowed it down to some issue with paths (the build process specifically copies some files from one directory to another and we suspected that it was copying them to the wrong directory).
Essentially, these are the problems in the way of making a full release of FastJet.

**Comment by lgray** [comment]
I think we're finally ready for this. We should do it!

**Comment by chrispap95** [comment]
Absolutely, I would love to get a release.

**Comment by lgray** [comment]
@chrispap95 I'll make an rc2 - then you can test it to make sure your analysis works. Then we can make `3.4.0.0`.

**Comment by chrispap95** [comment]
sounds good!

**Comment by henryiii** [comment]
What! You are actually using a release candidate as a candidate for a release? What devilry is this?

CC @jpivarski

**Comment by lgray** [comment]
OK `3.4.0.0rc2` is coming  @chrispap95 give it a try when it is done!

**Comment by henryiii** [comment]
Have we tried reenabling macOS now that the bugs are fixed?

**Comment by lgray** [comment]
I don't wanna poke the beehive that much, as they've just quieted down. I'll launch a PR to see. We should make a release for linux regardless.

**Comment by lgray** [comment]
@chrispap95 when you're done testing in realistic analysis ping here and I'll mint the non-rc release.

**Comment by chrispap95** [comment]
I tried it with some skimmed datasets and everything looks okay thus far. We plan to test this at scale with @chadfreer and @lucalavezzo soon.

**Comment by chrispap95** [comment]
Hi @lgray, today I tried running `rc2` at scale with about 260 GB of QCD MC. I haven't seen any fastjet-related problems up to now. I might also try with the full dataset (about 3 TB) later, but I am tempted to declare this release free of any major issues.

**Comment by lgray** [comment]
Plots all look reasonable as well?

**Comment by chrispap95** [comment]
Plots look reasonable for the submissions on the skimmed datasets (much smaller in size but still they were having issues before). I haven't made any plots for the large submission yet because I was having some dask-related issues on coffea-casa. I am rerunning now on cmslpc. I will get back once I make them, but I don't expect any surprises.

**Comment by chrispap95** [comment]
Not at all. I think would have seen it by now.

**Comment by lgray** [comment]
🎉
